const stories = {
  //if picked all A side

  -Welcome1A: "Pick Kenneth: He is born to be the great ruler and protector of Epicodus. Picking the good side could prevent the prophecy to happen. Tragic adventure awaits for this young man.",
  I-Chapter1A: "It was said that only the next prince can save Epicodus and stop the prophecy being fulfilled from Ethan's power. The powers of the fate blessed Kenneth with special powers. Each power has special effect. Choose wisely below from the giving options:",
  II-Chapter1A2A: "LoudMouth: chant cursed words that whoever hears it becomes petrified.",
  III-Chapter2Narrate: "21 Years have passed and Kenneth grew and became a strong independent person. As a preparation, Dudu made sure his son, Kenneth would grow into a powerful Prince and save Epicodus from the prophecy one day.",
  IV-Chapter2A: "When Kenneth was in a confused situation when he realized that he has to protect Epicodus. He accidentally used loudmouth and killed people. This caused trauma to the civilians resulting into a riot and chaos afterwards. He later then isolated himself from the castle to find his true self and decided that he needs proper training of the mind as well",
  V-Chapter3A: "He visited the Great Temple of Boujee and trained",
  VI-Chapter3ANarrate: "Along Kenneth’s Journey, he met Nicole and fell in love from 0-100. “I’ve never met a strong beautiful woman like you. You make me feel some type of way.” Nicole live as an average person in Epicodus. She won the jackpot if she’ll marry the future prince of Epicodus. But for Kenneth, his parents’ standards are beyond the expectations. There is no way that they will get married with they approval. Hence, they need to keep the situation private",
  VII-Chapter4Narrate: "As the story comes to an end, the fate of the two must come into conclusion. And the lives of people from Epicodus lies within Kenneth, the supposes protector. Given with his free will he has to choose which path will he lead.",
  VIII-Chapter3A4A: "Bring out the Romance!", //choices
  IX-Chapter4A: " Kenneth professed his love to Nicole and asked his father, Dudu for a blessing. The king rejected the offer and has gon crazy to hear the hasty decision. Kenneth and Nicole have been outcasted, breaking the rules of their bloodline and as well as the Kingdom’s commandment",
  X-Chapter4A5A: "Escape reality and live on your freewill", //choices
  X-Chapter4A5B: "Fight and be a Hero", //choices
  XI-Chapter5Narrate: "The Prophecy is here! The time has come! The final answer is soon to be known. Will Kenneth break the prophecy? Or will Ethan fulfill it instead?",
  XII-Chapter5A: "The prophecy has come, and the city of Epicodus starts to fall apart. Chaos are everywhere and people are dying. Kenneth felt despair and hopeless and has been swallowed in fear. He fled Epicodus with Nicole. Kenneth failed to save Epicodus and be the Ruler Prince. He relocated to CodeFellows and started a new life with Nicole and leave the past behind. END.",
//if picked all B from kenneth side

  II-Chapter1A2B: "CopyPaste: perfect copy of anything he sees",
  //III goes here..
  IV-Chapter2B: "Kenneth made an exact copy of Him in order to protect his own self from dying. The prophecy is being fulfilled now and he needs to do whatever he can to protect his own city.Manning up by doubling him can match up with whoever give threat to the City",
  //V VI and VII goes here..
  VIII-Chapter3A4B: "Fight alone",//choices
  IX-Chapter4B: "Kenneth will give his everything in order to protect Epicodus. He prepared long time and put in commitment on his life. He realized no one can stop the prophecy being fulfilled except by him. “I rather destroy myself than build a city again that I had to protect the first place”. Kenneth decided he has to let go of Nicole, in order to protect her as well. He made a perfect copy of him to go with Nicole in order to escape far away from Epicodus. (perfectcopy only lasts for a day).",
  X-Chapter4B5B: "You made the right path, Bro code on fleek son", //choices
  XI-Chapter5BNarrate: "Epicodus is in the verge of being destroyed, will Kenneth pull the last victory card? Or will Ethan got the last laugh? Choose the proper ending for your own purpose of tragic story",
  XII-Chapter5B1: "Ethan succeeded on bringing down the castle by the help of AJ. When he tried to kill the King he had a confession that shocked him. Dudu told Ethan that he was the long lost brother of Kenneth. He also had the same forsaken love with a villager. They had a kid before getting forced to marry Julie. They gave fruit to a boy named, Ethan and had to keep memories in private. Dudu feared that he will get overthrown if Amkhokar overhear the fragile situation. He casted out his fellow lover away from Epicodus along with Ethan. She later soon died of cancer, which causing Ethan to be adopted by the Foster’s home. Confused and shocked on what he heard. He used all his power to kill the King. The queen intervene but it was already too late. Aj quick enough to grab the queen and struck her between the chest. Now, they head to face the last man standing, Kenneth. They battled fiercely and violently. Causing the city to tremble, sides by sides they rumble.",
   XII-Chapter5B2: "Ethan brought out Nicole he held her hostage before sabotaging the castle. Ethan said 'You’ve been given choices quite a long time, but this time, I CHOSE to choose what to CHOOSE now. There’s only one winner, BROTHER.' Kenneth surrendered to promise not to hurt her. Aj found this perfect opportunity to take down Kenneth, he quickly used his special power. Then Ethan gave the final blow, causing instant fatality for Kenneth. He fulfilled the prophecy and Epicodus is now fallen into his hands.Welcome to the DARK SIDE!",

  //if picked B side
  -Welcome1B: "Pick Ethan: He is an adopted son and came from poor family. He has a strong hatred for Epicodus for not being able to help the poor. He wants to take upon revenge and destroy Epicodus.",
  Chapter1B: "The prophecy was called 'Bruhh-kery', where it will bring chaos, famine, disease, and unknown terrors to Epicodus.  They’ve been expecting this to come on the right time. Ethan was also chosen to fulfill the said prophecy, and it blessed him a special power. Choose below:",
  Chapter1B2C: "Chainsmoke: exhales a powerful poisoned fume that causes fatal damage", //choices
  Chapter2CNarrate: "21 Years have passed and Ethan's hatred grew and became a strong malevolent person. He became stronger when he discovered that he can maximize his power by absorbing people’s energy.",
  Chapter2C: "Ethan made a strategic plan on bringing down Epicodus. He thought of poisoning all people in Epicodus so they can feel the pain and the suffering especially for those rich people that never helped the poor, he disgusts them a lot and does not pity nor mercy",
  Chapter3B: "Bring chaos to Epicodus",
  Chapter3BNarrate: "Eversince then Ethan’s been alone  and never had any friends neither family. He came into a realization that, in order to fully destroy Epicodus he needs somebody to pair up with him and somebody who can relate and obey his commands. He later then encountered, a same being with the same passion and insanity as him. He recruited the being named, “AJ”. Whom has the power to tell jokes and whoever hears it, goes insane. He also have a special talent where he can fart out fire.",
  Chapter3B4C: "Bring upon destruction towards Epicodus along with AJ",
  Chapter4C: "Ethan Decided to strike the castle first and bring punishment upon Kenneth’s family. He brought his partner AJ to make things faster and quick",
  //Chapter5BNarrate and Chapter5B goes here

  //if 5C chosen
  Chapter5C1: "Ethan succeeded on bringing down the castle with the help of AJ. When he tried to kill the King, he had a confession that shocked him. Dudu told Ethan that he was the long lost brother of Kenneth. He also had the same forsaken love with a villager. They had a kid before getting forced to marry Julie. They gave fruit to a boy named, Ethan and had to keep memories in private. Dudu feared that he will get overthrown if Amkhokar knows the illegal situation. He casted out his fellow lover away from Epicodus along with Ethan. She later soon died of cancer, which causing Ethan to be adopted by the Foster’s home. Confused and shocked on what he heard. He used all his power to kill the King. The queen intervene but it was already too late. Aj quick enough to grab the queen and struck her between the chest. Before he kills her, AJ hesitated and made her a hostage. Meanwhile, Ethan is almost close to fulfilling the prophecy. And also making Nicole a hostage in current situation.",
  Chapter5C2:"Kenneth is pretty much hopeless, ran out of options to fight. Kenneth, seeing his mom and lover at the same time held hostage is too much sacrifice for him. He knows he cannot save both. Ethan said 'AJ, I have been with you since day one. I will make you my right hand after you finish off Kenneth.'. Aj had flashbacks of his childhood. He has a trauma of being lied to. When he was a kid, he had a best-friend named, Kavod. Him and Kavod have been close friends, for AJ they were. Kavod is a trickster. He likes to make his friends his ‘slave’ by commanding them to do such acts with a promise equivalent to something they would agree to. AJ thought of being controlled like a puppet, like before. He flashes in a speed of light by the maximizing oxygen and bursting it out. He instantly stabbed Ethan’s heart. Ethan then shocked on what just happened. Kenneth found this a perfect opening to protect the Queen and his lover. He used his final maximized power onto AJ.",
  Chapter5C3: "Aj got wiped and the prophecy has been broken. Kenneth successfully protected all his loved ones along the entire Epicodus. Ethan failed unexpectedly, he opened his eyes looks around and found out that Ethan said 'I overslept! I should’ve not watched Fifty Shades 1 and 2 sequel!!' Ethan looks for his phone and message his close friend. To: Kenneth message: 'BRO, SIGN ME IN!'"

}
