const stories = {
  Welcome: "Long time ago, there a was a boy named Kenneth. He's the future prince of Epicodus. Coming from a royal family, he inherits the bloodline of Amkhokar the son of Dudu. And the queen Julie, the current wife of Dudu. He was destined to rule out Epicodus and bring a new life to a new generation, but there was only one problem. Ethan is coming to doom Epicodus, the fulfiller of the great prophecy. To continue the story pick a side that you want to start with:",
  Welcome1A: "Pick Kenneth: He is born to be the great ruler and protector of Epicodus. Picking the good side could prevent the prophecy to happen. Tragic adventure awaits for this young man.",
  Welcome1B: "Pick Ethan: He is an adopted son and came from poor family. He has a strong hatred for Epicodus for not being able to help the poor. He wants to take upon revenge and destroy Epicodus.",
  Chapter1A: "It was said that only the next prince can save Epicodus and stop the prophecy being fulfilled from Ethan’s power. The powers of the fate blessed Kenneth with special powers. Each power has special effect. Choose wisely below from the giving options:",
  Chapter1A2A: "LoudMouth: chant cursed words that whoever hears it becomes petrified.",
  Chapter1A2B: "CopyPaste: perfect copy of anything he sees",
  Chapter1B: "The prophecy was called 'Bruhh-kery', where it will bring chaos, famine, disease, and unknown terrors to Epicodus.  They’ve been expecting this to come on the right time. Ethan was also chosen to fulfill the said prophecy, and it blessed him a special power. Choose below:",
  Chapter1B2C: "Chainsmoke: exhales a powerful poisoned fume that causes fatal damage",
  Chapter1B2D: "Git-Clone-no-jutsu: can multiply himself many times",
  Chapter2ANarrate: "21 Years have passed and Kenneth grew and became a strong independent person. As a preparation, Dudu made sure his son, Kenneth would grow into a powerful Prince and save Epicodus from the prophecy one day. Would you like to continue the story with a twist of love or be a man and just do it?",
  Chapter2A: "When Kenneth was in a confused situation when he realized that he has to protect Epicodus. He accidentally used loudmouth and killed people. This caused trauma to the civilians resulting into a riot and chaos afterwards. He later then isolated himself from the castle to find his true self and decided that he needs proper training of the mind as well",
  Chapter2A3A: "He visited the Great Temple of Boujee and trained",
  Chapter2B: "Kenneth made an exact copy of Him in order to protect his own self from dying. The prophecy is being fulfilled now and he needs to do whatever he can to protect his own city.Manning up by doubling him can match up with whoever give threat to the City",
  Chapter2B3A: "One of his clone encountered a woman in deep danger. He rushed to help",
  Chapter2BNarrate: "21 Years have passed and Ethan’s hatred grew and became a strong malevolent person. He became stronger when he discovered that he can maximize his power by absorbing people’s energy.",
  Chapter2C: "Ethan made a strategic plan on bringing down Epicodus. He thought of poisoning all people in Epicodus so they can feel the pain and the suffering especially for those rich people that never helped the poor, he disgusts them a lot and does not pity nor mercy",
  Chapter2C3A: "Execute out the Plan",
  Chapter2D: "Ethan thought of cloning himself so that he can damage Epicodus in multiple casualties as possible. Obeying the order of the so called “Bruhh-kery”. Torturing people will be the best way to feel what is ‘hatred’ is like and what real ‘pain’ feel like. Becoming the new god of Epicodus is to come",
  Chapter2D3A: "Bring chaos to Epicodus",
  Chapter3A: "Along Kenneth’s Journey, he met Nicole and fell in love from 0-100. “I’ve never met a strong beautiful woman like you. You make me feel some type of way.” Nicole live as an average person in Epicodus. She won the jackpot if she’ll marry the future prince of Epicodus. But for Kenneth, his parents’ standards are beyond the expectations. There is no way that they will get married with they approval. Hence, they need to keep the situation private",
  Chapter3A4A: "Bring out the Romance!",
  Chapter3A4B: "",
  Chapter3B: "21 years have passed and Ethan grew alone and realized that in order to fully destroy Epicodus he needs somebody to pair up with him. He then encountered a same being with the same hatred as him so he recruited the being named, “AJ”. This being has the power to tell jokes and whoever listens to it get mentally insane and controlled by him",
  Chapter3B4C: "Bring upon destruction towards Epicodus along with AJ, who will be the one to control the People?",
  Chapter4Narrater, "As the story comes to an end, the fate of the two must come into conclusion. And the lives of people from Epicodus lies within Kenneth, the supposes protector. Given with his free will he has to choose which path will he lead.",
  Chapter4A: " Kenneth professed his love to Nicole and asked his father, Dudu for a blessing. The king rejected the offer and has gon crazy to hear the hasty decision. Kenneth and Nicole have been outcasted, breaking the rules of their bloodline and as well as the Kingdom’s commandment",
  Chapter4A5A: "",
  Chapter4A5B: "",
  Chapter4B: "",
  Chapter4B5B: "",
  Chapter4C: "",
  Chapter4C5B: "",
  Chapter4C5C: "",
  Chapter5A: "",
  Chapter5B: "",
  Chapter5C: ""
}